repos:
- repo: local
  hooks:
    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: python
      types: [python]
      require_serial: true

    - id: ruff-lint
      name: ruff lint
      entry: ruff check --fix
      language: python
      types: [python]
      require_serial: true
    
    - id: isort
      name: isort
      entry: isort
      language: python
      types: [python]
      args: ["--profile", "black"]

    - id: mypy
      name: mypy
      entry: "./run-mypy.sh"
      language: python
      types: [python]
